INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'가천대학교', '경기', '100276', 'PNG_2.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'가톨릭관동대학교', '강원', '100278', 'PNG_3.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'가톨릭대학교', '경기', '100276', 'PNG_4.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'가톨릭상지대학교', '경북', '100285', 'PNG_5.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'감리교신학대학교', '서울', '100260', 'PNG_6.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강남대학교', '경기', '100276', 'PNG_7.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강동대학교', '충북', '100280', 'PNG_8.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강릉영동대학교', '강원', '100278', 'PNG_9.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강릉원주대학교', '강원', '100278', 'PNG_10.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강원관광대학교', '강원', '100278', 'PNG_11.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강원대학교', '강원', '100278', 'PNG_12.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'강원도립대학교', '강원', '100278', 'PNG_13.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'거제대학교', '경남', '100291', 'PNG_14.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'건국대학교', '서울', '100260', 'PNG_15.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'건국대학교(글로컬)', '충북', '100280');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'건양대학교', '충남', '100281', 'PNG_16.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'건양사이버대학교', '대전', '100271', 'PNG_344.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경기과학기술대학교', '경기', '100276', 'PNG_17.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경기대학교', '경기', '100276', 'PNG_18.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경남과학기술대학교', '경남', '100291', 'PNG_19.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경남대학교', '경남', '100291', 'PNG_20.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경남정보대학교', '부산', '100267', 'PNG_23.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경동대학교', '강원', '100278', 'PNG_25.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경민대학교', '경기', '100276', 'PNG_26.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경복대학교', '경기', '100276', 'PNG_27.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경북과학대학교', '경북', '100285', 'PNG_28.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경북대학교', '대구', '100272', 'PNG_29.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경북도립대학교', '경북', '100285', 'PNG_30.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경북전문대학교', '경북', '100285', 'PNG_31.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경성대학교', '부산', '100267', 'PNG_33.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경운대학교', '경북', '100285', 'PNG_34.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'경운대학교(산업대)', '경북', '100285');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경인교육대학교', '인천', '100269', 'PNG_35.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경인여자대학교', '인천', '100269', 'PNG_36.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경일대학교', '경북', '100285', 'PNG_37.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경주대학교', '경북', '100285', 'PNG_38.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경희대학교', '서울', '100260', 'PNG_40.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'경희사이버대학교', '서울', '100260', 'PNG_345.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'계명대학교', '대구', '100272', 'PNG_41.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'계명문화대학교', '대구', '100272', 'PNG_42.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'계원예술대학교', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'고구려대학교', '전남', '100283', 'PNG_44.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'고려대학교', '서울', '100260', 'PNG_45.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'고려사이버대학교', '서울', '100260', 'PNG_346.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'고신대학교', '부산', '100267', 'PNG_46.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'공주교육대학교', '충남', '100281', 'PNG_48.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'공주대학교', '충남', '100281', 'PNG_49.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광신대학교', '광주', '100275', 'PNG_50.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광양보건대학교', '전남', '100283', 'PNG_51.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광운대학교', '서울', '100260', 'PNG_52.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광주가톨릭대학교', '전남', '100283', 'PNG_53.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광주교육대학교', '광주', '100275', 'PNG_55.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광주대학교', '광주', '100275', 'PNG_56.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광주보건대학교', '광주', '100275', 'PNG_57.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'광주여자대학교', '광주', '100275', 'PNG_58.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'구미대학교', '경북', '100285', 'PNG_59.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'국민대학교', '서울', '100260', 'PNG_61.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'국제대학교', '경기', '100276', 'PNG_62.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'국제사이버대학교', '경기', '100276', 'PNG_347.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'군산간호대학교', '전북', '100282', 'PNG_63.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'군산대학교', '전북', '100282', 'PNG_64.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'군장대학교', '전북', '100282', 'PNG_65.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'극동대학교', '충북', '100280', 'PNG_67.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'글로벌사이버대학교', '충남', '100281', 'PNG_348.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'금강대학교', '충남', '100281', 'PNG_68.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'금오공과대학교', '경북', '100285', 'PNG_69.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'기독간호대학교', '광주', '100275', 'PNG_70.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'김천대학교', '경북', '100285', 'PNG_72.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'김포대학교', '경기', '100276', 'PNG_73.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'김해대학교', '경남', '100291', 'PNG_74.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'나사렛대학교', '충남', '100281', 'PNG_76.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'남부대학교', '광주', '100275', 'PNG_77.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'남서울대학교', '충남', '100281', 'PNG_78.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'남서울대학교(산업대)', '충남', '100281');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'농협대학교', '경기', '100276', 'PNG_79.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'단국대학교', '경기', '100276', 'PNG_80.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대경대학교', '경북', '100285', 'PNG_81.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구가톨릭대학교', '경북', '100285', 'PNG_82.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구공업대학교', '대구', '100272', 'PNG_84.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구과학대학교', '대구', '100272', 'PNG_85.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구교육대학교', '대구', '100272', 'PNG_86.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구대학교', '경북', '100285', 'PNG_87.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구보건대학교', '대구', '100272', 'PNG_89.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구사이버대학교', '경북', '100285', 'PNG_349.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구예술대학교', '경북', '100285', 'PNG_90.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대구한의대학교', '경북', '100285', 'PNG_92.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대덕대학교', '대전', '100271', 'PNG_93.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대동대학교', '부산', '100267', 'PNG_94.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대림대학교', '경기', '100276', 'PNG_95.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대신대학교', '경북', '100285', 'PNG_96.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대원대학교', '충북', '100280', 'PNG_97.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대전대학교', '대전', '100271', 'PNG_99.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대전보건대학교', '대전', '100271', 'PNG_100.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대전신학대학교', '대전', '100271', 'PNG_101.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'대진대학교', '경기', '100276', 'PNG_102.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'덕성여자대학교', '서울', '100260', 'PNG_103.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동강대학교', '광주', '100275', 'PNG_104.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동국대학교', '서울', '100260', 'PNG_105.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'동국대학교(경주)', '경북', '100285');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동남보건대학교', '경기', '100276', 'PNG_106.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동덕여자대학교', '서울', '100260', 'PNG_107.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동명대학교', '부산', '100267', 'PNG_108.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동서대학교', '부산', '100267', 'PNG_110.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동서울대학교', '경기', '100276', 'PNG_111.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동신대학교', '전남', '100283', 'PNG_112.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동아대학교', '부산', '100267', 'PNG_113.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동아방송예술대학교', '경기', '100276', 'PNG_114.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동양대학교', '경북', '100285', 'PNG_116.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동양미래대학교', '서울', '100260', 'PNG_117.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동원과학기술대학교', '경남', '100291', 'PNG_118.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동원대학교', '경기', '100276', 'PNG_119.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동의과학대학교', '부산', '100267', 'PNG_120.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동의대학교', '부산', '100267', 'PNG_121.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'동주대학교', '부산', '100267', 'PNG_122.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'두원공과대학교', '경기', '100276', 'PNG_123.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'디지털서울문화예술대학교', '서울', '100260', 'PNG_350.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'루터대학교', '경기', '100276', 'PNG_124.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'마산대학교', '경남', '100291', 'PNG_125.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'명지대학교', '경기', '100276', 'PNG_126.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'목원대학교', '대전', '100271', 'PNG_127.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'목포가톨릭대학교', '전남', '100283', 'PNG_128.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'목포과학대학교', '전남', '100283', 'PNG_129.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'목포대학교', '전남', '100283', 'PNG_130.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'목포해양대학교', '전남', '100283', 'PNG_131.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'문경대학교', '경북', '100285', 'PNG_132.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'배재대학교', '대전', '100271', 'PNG_133.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'배화여자대학교', '서울', '100260', 'PNG_134.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'백석대학교', '충남', '100281', 'PNG_135.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'백석문화대학교', '충남', '100281', 'PNG_136.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'백제예술대학교', '전북', '100282', 'PNG_137.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산가톨릭대학교', '부산', '100267', 'PNG_139.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산경상대학교', '부산', '100267', 'PNG_140.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산과학기술대학교', '부산', '100267', 'PNG_141.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산교육대학교', '부산', '100267', 'PNG_142.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산대학교', '부산', '100267', 'PNG_143.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산디지털대학교', '부산', '100267', 'PNG_351.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산여자대학교', '부산', '100267', 'PNG_144.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산예술대학교', '부산', '100267', 'PNG_145.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'부산외국어대학교', '부산', '100267');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부산장신대학교', '경남', '100291', 'PNG_147.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'부천대학교', '경기', '100276', 'PNG_148.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'사이버한국외국어대학교', '서울', '100260', 'PNG_352.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'삼육대학교', '서울', '100260', 'PNG_149.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'삼육보건대학교', '서울', '100260', 'PNG_150.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'상명대학교', '서울', '100260', 'PNG_151.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'상지대학교', '강원', '100278', 'PNG_152.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'상지영서대학교', '강원', '100278', 'PNG_153.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서강대학교', '서울', '100260', 'PNG_154.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서경대학교', '서울', '100260', 'PNG_155.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서라벌대학교', '경북', '100285', 'PNG_157.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서영대학교', '광주', '100275', 'PNG_158.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울과학기술대학교', '서울', '100260', 'PNG_159.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울교육대학교', '서울', '100260', 'PNG_160.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울기독대학교', '서울', '100260', 'PNG_161.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울대학교', '서울', '100260', 'PNG_162.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울디지털대학교', '서울', '100260', 'PNG_353.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울사이버대학교', '서울', '100260', 'PNG_354.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울시립대학교', '서울', '100260', 'PNG_163.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울신학대학교', '경기', '100276', 'PNG_164.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울여자간호대학교', '서울', '100260', 'PNG_166.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울여자대학교', '서울', '100260', 'PNG_165.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울예술대학교', '경기', '100276', 'PNG_167.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서울장신대학교', '경기', '100276', 'PNG_168.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서원대학교', '충북', '100280', 'PNG_169.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서일대학교', '서울', '100260', 'PNG_170.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'서정대학교', '경기', '100276', 'PNG_171.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'선린대학교', '경북', '100285', 'PNG_173.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'선문대학교', '충남', '100281', 'PNG_174.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'성결대학교', '경기', '100276', 'PNG_175.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'성공회대학교', '서울', '100260', 'PNG_176.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'성균관대학교', '서울', '100260', 'PNG_177.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'성신여자대학교', '서울', '100260');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'세경대학교', '강원', '100278', 'PNG_179.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'세명대학교', '충북', '100280', 'PNG_180.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'세종대학교', '서울', '100260', 'PNG_181.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'세종사이버대학교', '서울', '100260', 'PNG_355.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'세한대학교', '전남', '100283', 'PNG_182.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'송곡대학교', '강원', '100278', 'PNG_183.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'송원대학교', '광주', '100275', 'PNG_184.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'송호대학교', '강원', '100278', 'PNG_185.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'수성대학교', '대구', '100272', 'PNG_186.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'수원가톨릭대학교', '경기', '100276', 'PNG_187.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'수원과학대학교', '경기', '100276', 'PNG_188.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'수원대학교', '경기', '100276', 'PNG_189.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'수원여자대학교', '경기', '100276', 'PNG_190.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'숙명여자대학교', '서울', '100260', 'PNG_191.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'순복음총회신학교', '충북', '100280');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'순천대학교', '전남', '100283', 'PNG_192.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'순천제일대학교', '전남', '100283', 'PNG_193.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'순천향대학교', '충남', '100281', 'PNG_194.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'숭실대학교', '서울', '100260', 'PNG_195.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'숭실사이버대학교', '서울', '100260', 'PNG_356.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'숭의여자대학교', '서울', '100260', 'PNG_196.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'신경대학교', '경기', '100276', 'PNG_197.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'신구대학교', '경기', '100276', 'PNG_198.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'신라대학교', '부산', '100267', 'PNG_199.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'신성대학교', '충남', '100281', 'PNG_200.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'신안산대학교', '경기', '100276', 'PNG_201.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'아주대학교', '경기', '100276', 'PNG_204.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'안동과학대학교', '경북', '100285', 'PNG_206.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'안동대학교', '경북', '100285', 'PNG_207.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'안산대학교', '경기', '100276', 'PNG_208.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'안양대학교', '경기', '100276', 'PNG_209.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'여주대학교', '경기', '100276', 'PNG_210.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'연성대학교', '경기', '100276', 'PNG_211.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'연세대학교', '서울', '100260', 'PNG_212.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'연암공과대학교', '경남', '100291');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영남대학교', '경북', '100285', 'PNG_214.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영남신학대학교', '경북', '100285', 'PNG_215.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영남이공대학교', '대구', '100272', 'PNG_217.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영산대학교', '경남', '100291', 'PNG_219.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영산선학대학교', '전남', '100283', 'PNG_220.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영진사이버대학교', '대구', '100272', 'PNG_361.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영진전문대학교', '대구', '100272', 'PNG_221.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'예수대학교', '전북', '100282', 'PNG_222.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'예원예술대학교', '전북', '100282', 'PNG_223.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'오산대학교', '경기', '100276', 'PNG_224.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'용인대학교', '경기', '100276', 'PNG_225.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'우석대학교', '전북', '100282', 'PNG_227.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'우송대학교', '대전', '100271', 'PNG_228.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'우송대학교(산업대)', '대전', '100271');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'울산과학대학교', '울산', '100273', 'PNG_231.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'울산대학교', '울산', '100273', 'PNG_232.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'웅지세무대학교', '경기', '100276', 'PNG_233.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'원광대학교', '전북', '100282', 'PNG_234.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'원광디지털대학교', '전북', '100282', 'PNG_358.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'원광보건대학교', '전북', '100282');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'위덕대학교', '경북', '100285', 'PNG_235.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'유원대학교', '충북', '100280');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'유한대학교', '경기', '100276', 'PNG_236.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'을지대학교', '대전', '100271', 'PNG_238.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'이화여자대학교', '서울', '100260', 'PNG_239.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인덕대학교', '서울', '100260', 'PNG_240.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인제대학교', '경남', '100291', 'PNG_241.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인천가톨릭대학교', '인천', '100269', 'PNG_242.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인천대학교', '인천', '100269', 'PNG_243.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인천재능대학교', '인천', '100269', 'PNG_244.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인하대학교', '인천', '100269', 'PNG_246.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'장로회신학대학교', '서울', '100260', 'PNG_247.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'장안대학교', '경기', '100276', 'PNG_248.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전남과학대학교', '전남', '100283', 'PNG_249.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전남대학교', '광주', '100275', 'PNG_250.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전남도립대학교', '전남', '100283', 'PNG_251.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전북과학대학교', '전북', '100282', 'PNG_252.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전북대학교', '전북', '100282', 'PNG_253.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전주교육대학교', '전북', '100282', 'PNG_254.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전주대학교', '전북', '100282', 'PNG_256.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전주비전대학교', '전북', '100282', 'PNG_257.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'제주관광대학교', '제주', '100292', 'PNG_258.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'제주국제대학교', '제주', '100292', 'PNG_259.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'제주대학교', '제주', '100292', 'PNG_260.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'제주한라대학교', '제주', '100292', 'PNG_261.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'조선간호대학교', '광주', '100275', 'PNG_262.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'조선대학교', '광주', '100275', 'PNG_263.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'조선이공대학교', '광주', '100275', 'PNG_264.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'중부대학교', '충남', '100281', 'PNG_265.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'중앙대학교', '경기', '100276', 'PNG_266.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'중앙승가대학교', '경기', '100276', 'PNG_267.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'중원대학교', '충북', '100280', 'PNG_268.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'진주교육대학교', '경남', '100291', 'PNG_269.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'진주보건대학교', '경남', '100291', 'PNG_270.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'진주산업대학교(산업대)', '경남', '100291');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'차의과학대학교', '경기', '100276', 'PNG_271.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'창신대학교', '경남', '100291', 'PNG_272.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'창원대학교', '경남', '100291', 'PNG_273.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'창원문성대학교', '경남', '100291', 'PNG_274.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'청강문화산업대학교', '경기', '100276', 'PNG_276.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'청암대학교', '전남', '100283', 'PNG_277.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'청운대학교', '충남', '100281', 'PNG_278.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'청주교육대학교', '충북', '100280', 'PNG_279.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'청주대학교', '충북', '100280', 'PNG_280.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'초당대학교', '전남', '100283', 'PNG_281.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'초당대학교(산업대)', '전남', '100283');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'총신대학교', '서울', '100260', 'PNG_282.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'추계예술대학교', '서울', '100260', 'PNG_283.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'춘천교육대학교', '강원', '100278', 'PNG_284.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'춘해보건대학교', '울산', '100273', 'PNG_285.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'충남대학교', '대전', '100271', 'PNG_286.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'충북대학교', '충북', '100280', 'PNG_288.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'충북도립대학교', '충북', '100280', 'PNG_289.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'충북보건과학대학교', '충북', '100280', 'PNG_290.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'충청대학교', '충북', '100280', 'PNG_291.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'칼빈대학교', '경기', '100276', 'PNG_293.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'평택대학교', '경기', '100276', 'PNG_294.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'포항대학교', '경북', '100285', 'PNG_296.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한경대학교', '경기', '100276', 'PNG_297.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한경대학교(산업대)', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국골프대학교', '강원', '100278', 'PNG_298.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국관광대학교', '경기', '100276', 'PNG_300.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국교원대학교', '충북', '100280', 'PNG_301.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국교통대학교', '충북', '100280', 'PNG_302.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국국제대학교', '경남', '100291', 'PNG_303.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국기술교육대학교', '충남', '100281', 'PNG_304.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국방송통신대학교', '서울', '100260', 'PNG_366.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국복지대학교', '경기', '100276', 'PNG_306.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국산업기술대학교(산업대)', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국성서대학교', '서울', '100260', 'PNG_308.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국승강기대학교', '경남', '100291', 'PNG_309.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국예술종합학교', '서울', '100260', 'PNG_364.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국외국어대학교', '서울', '100260');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국전통문화대학교', '충남', '100281');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국체육대학교', '서울', '100260', 'PNG_312.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국항공대학교', '경기', '100276', 'PNG_313.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한남대학교', '대전', '100271', 'PNG_315.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한동대학교', '경북', '100285', 'PNG_316.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한라대학교', '강원', '100278', 'PNG_317.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한림대학교', '강원', '100278', 'PNG_319.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한림성심대학교', '강원', '100278', 'PNG_320.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한밭대학교', '대전', '100271', 'PNG_321.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한밭대학교(산업대)', '대전', '100271');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한서대학교', '충남', '100281', 'PNG_322.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한성대학교', '서울', '100260', 'PNG_323.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한세대학교', '경기', '100276', 'PNG_324.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한신대학교', '경기', '100276', 'PNG_325.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한양대학교', '서울', '100260', 'PNG_326.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한양대학교(ERICA)', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한양사이버대학교', '서울', '100260', 'PNG_359.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한양여자대학교', '서울', '100260', 'PNG_327.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한영대학교', '전남', '100283', 'PNG_328.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한일장신대학교', '전북', '100282', 'PNG_330.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'협성대학교', '경기', '100276', 'PNG_333.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'혜전대학교', '충남', '100281', 'PNG_334.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'호남대학교', '광주', '100275', 'PNG_336.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'호남신학대학교', '광주', '100275', 'PNG_338.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'호서대학교', '충남', '100281', 'PNG_340.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'호원대학교', '전북', '100282', 'PNG_341.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'홍익대학교', '서울', '100260', 'PNG_342.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'화신사이버대학교', '부산', '100267', 'PNG_360.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'열린사이버대학교', '서울', '100260', 'PNG_357.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'영남외국어대학교', '경북', '100285', 'PNG_216.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'영산대학교(산업대)', '부산', '100267');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'용인송담대학교', '경기', '100276', 'PNG_226.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'우송공업대학교', '대전', '100271');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'우송정보대학교', '대전', '100271', 'PNG_229.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'원주대학교', '강원', '100278');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'인천전문대학교', '인천', '100269');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'인하공업전문대학교', '인천', '100269', 'PNG_245.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'적십자간호대학교', '서울', '100260');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'전주기전대학교', '전북', '100282', 'PNG_255.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'정석대학교', '서울', '100260');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'제주교육대학교', '제주', '100292');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'제주산업정보대학교', '제주', '100292');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'중앙대학교(안성)', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'천안연암대학교', '충남', '100281', 'PNG_275.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'충남도립청양대학교', '충남', '100281', 'PNG_287.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국침례신학대학교', '대전', '100271');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'탐라대학교', '제주', '100292');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국교통대학교(산업대)', '충북', '100280');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국농수산대학교', '전북', '100282');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국복지사이버대학교', '경북', '100285', 'PNG_362.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국산업기술대학교', '경기', '100276', 'PNG_307.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국정보통신기능대학교', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한국철도대학교', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한국폴리텍대학교', '인천', '100269', 'PNG_363.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'국립한국해양대학교', '부산', '100267');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한려대학교', '전남', '100283', 'PNG_318.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'한북대학교', '경기', '100276');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'한영신학대학교', '서울', '100260', 'PNG_329.png');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'혜천대학교', '대전', '100271', 'PNG_335.png');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'DGIST', '대구', '100272');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'GIST', '광주', '100275');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'KAIST', '대전', '100271');
INSERT INTO university (id, school_name, region, region_code) VALUES (university_sequence.nextval,'POSTECH', '경북', '100285');
INSERT INTO university (id, school_name, region, region_code, logo_img) VALUES (university_sequence.nextval,'UNIST', '울산', '100273', 'PNG_230.png');
